workflows:
  ios_ci:
    name: iOS CI (tanpa CocoaPods)
    max_build_duration: 60
    environment:
      xcode: latest

    triggering:
      events: [ push ]
      branch_patterns:
        - pattern: mealsapp-beforemodular
          include: true
          source: true

    scripts:
      - name: Debug layout
        script: |
          echo "PWD=$(pwd)"
          find . -maxdepth 1 -name "*.xcodeproj" -print
          find . -maxdepth 1 -name "*.xcworkspace" -print

      - name: Build for iOS Simulator
        script: |
          set -euo pipefail
          PROJ="$(find . -maxdepth 1 -name '*.xcodeproj' | head -n1)"
          xcodebuild \
            -project "$PROJ" \
            -scheme "MealsApp" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,OS=latest,name=iPhone 16' \
            clean build | xcpretty

    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Logs/**/*
