workflows:
  ios_ci:
    name: iOS CI (auto-detect path)
    max_build_duration: 60
    environment:
      xcode: latest

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: mealsapp-beforemodular
          include: true
          source: true

    scripts:
      - name: Debug layout
        script: |
          echo "PWD=$(pwd)"
          echo "=== Struktur repo ==="
          find . -maxdepth 2 -type f \( -name "*.xcodeproj" -o -name "*.xcworkspace" -o -name "Podfile" \)

      - name: Build for iOS Simulator (auto detect)
        script: |
          set -euo pipefail
          # Cari file proyek di root atau di subfolder MealsApp
          PROJECT_PATH="$(find . -maxdepth 2 -name '*.xcodeproj' | head -n1 || true)"
          WORKSPACE_PATH="$(find . -maxdepth 2 -name '*.xcworkspace' | head -n1 || true)"

          if [ -z "$WORKSPACE_PATH" ] && [ -z "$PROJECT_PATH" ]; then
            echo "❌ Tidak menemukan .xcodeproj / .xcworkspace."
            exit 1
          fi

          SCHEME_NAME="MealsApp"

          echo "Workspace: ${WORKSPACE_PATH:-<none>}"
          echo "Project  : ${PROJECT_PATH:-<none>}"
          echo "Scheme   : $SCHEME_NAME"

          if [ -n "$WORKSPACE_PATH" ]; then
            xcodebuild \
              -workspace "$WORKSPACE_PATH" \
              -scheme "$SCHEME_NAME" \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,OS=latest,name=iPhone 16' \
              clean build | xcpretty
          else
            xcodebuild \
              -project "$PROJECT_PATH" \
              -scheme "$SCHEME_NAME" \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,OS=latest,name=iPhone 16' \
              clean build | xcpretty
          fi

    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Logs/**/*
    publishing:
      email:
        recipients:
          - nunutech4.0@gmail.com
        notify:
          success: false
          failure: true
